#######################################################
## This is the default SkitChat configuration.       ##
## SkitChat v1.0 by chaseoes.                        ##
## http://dev.bukkit.org/server-mods/skitchat/       ##
#######################################################
settings:
  updatecheck: true
  logchatmessages: false
  logpms: true
  whitelistmessage: '&bThis server is whitelisted!'
  disabledeathmessages: false
  grammar:
    forcecapitalization: false
    forcepunctuation: false
    forcecapitalI: false
  spam:
    min-playercount: 5
    capspercent: 35
    caps-minchars: 4
    forcemove: true
    rejointime: 5
    chatdelay: 5
    nodupemessages: true
    nodupecommands: false
    noextraspaces: true
  urls:
    level: 1
    exceptions:
    - skitscape.com
chat:
  globalformat: '%p%dn&7: &f%m'
  global-join: '&e%dn has logged in.'
  global-leave: '&e%dn has logged out.'
  global-tabformat: '%dn'
  pm-from: '&7(From %dn&7): &f%m'
  pm-to: '&7(To %dn&7): &f%m'
  spyformat: '&7(Spy %from -> %to&7): &f%m'
  meformat: '%dn&b * &f%msg'
  friendcolor: '&a'
info:
  enable: false
  defaultgroup: 'default'
  defaultprefix: '[Prefix]'
  defaultsuffix: '[Suffix]'
groups:
  owner:
    chatformat: '%p%dn&7: &c%m'
    join: none
    leave: none
    tabformat: '&4%dn'
    prefix: none
    suffix: none
players:
